// Admin-specific mock data for the admin panel

export const adminStats = {
  totalUsers: 1247,
  usersChange: "+12%",
  stocksCreated: 48,
  stocksChange: "+8",
  stocksSold: 892,
  stocksSoldChange: "+24%",
  totalTransactions: 5834,
  transactionsChange: "+18%",
};

export const recentAdminTransactions = [
  {
    id: "tx-001",
    user: "John Smith",
    userId: "USR-1024",
    type: "buy",
    stock: "AAPL",
    stockName: "Apple Inc.",
    quantity: 15,
    price: 178.50,
    total: 2677.50,
    fee: 2.68,
    status: "completed",
    date: "2024-02-20T14:32:00",
  },
  {
    id: "tx-002",
    user: "Sarah Johnson",
    userId: "USR-1025",
    type: "sell",
    stock: "TSLA",
    stockName: "Tesla Inc.",
    quantity: 8,
    price: 245.00,
    total: 1960.00,
    fee: 1.96,
    status: "completed",
    date: "2024-02-20T13:15:00",
  },
  {
    id: "tx-003",
    user: "Michael Chen",
    userId: "USR-1026",
    type: "buy",
    stock: "NVDA",
    stockName: "NVIDIA Corp.",
    quantity: 5,
    price: 892.00,
    total: 4460.00,
    fee: 4.46,
    status: "pending",
    date: "2024-02-20T12:45:00",
  },
  {
    id: "tx-004",
    user: "Emily Davis",
    userId: "USR-1027",
    type: "buy",
    stock: "MSFT",
    stockName: "Microsoft Corp.",
    quantity: 20,
    price: 415.00,
    total: 8300.00,
    fee: 8.30,
    status: "completed",
    date: "2024-02-20T11:20:00",
  },
  {
    id: "tx-005",
    user: "Robert Wilson",
    userId: "USR-1028",
    type: "sell",
    stock: "GOOGL",
    stockName: "Alphabet Inc.",
    quantity: 3,
    price: 142.50,
    total: 427.50,
    fee: 0.43,
    status: "completed",
    date: "2024-02-20T10:05:00",
  },
  {
    id: "tx-006",
    user: "Lisa Brown",
    userId: "USR-1029",
    type: "buy",
    stock: "AMZN",
    stockName: "Amazon.com Inc.",
    quantity: 10,
    price: 185.75,
    total: 1857.50,
    fee: 1.86,
    status: "pending",
    date: "2024-02-20T09:30:00",
  },
  {
    id: "tx-007",
    user: "David Lee",
    userId: "USR-1030",
    type: "sell",
    stock: "META",
    stockName: "Meta Platforms",
    quantity: 12,
    price: 485.00,
    total: 5820.00,
    fee: 5.82,
    status: "completed",
    date: "2024-02-19T16:45:00",
  },
  {
    id: "tx-008",
    user: "Jennifer Taylor",
    userId: "USR-1031",
    type: "buy",
    stock: "NFLX",
    stockName: "Netflix Inc.",
    quantity: 6,
    price: 625.00,
    total: 3750.00,
    fee: 3.75,
    status: "completed",
    date: "2024-02-19T15:20:00",
  },
];

export const adminNavLinks = [
  {
    page: "Overview",
    icon: "mdi:view-dashboard-outline",
    href: "/admin/overview",
  },
  {
    page: "Users",
    icon: "mdi:users-outline",
    href: "/admin/users",
  },
  {
    page: "All Stocks",
    icon: "mdi:chart-line-variant",
    href: "/admin/stocks",
  },
  {
    page: "Orders",
    icon: "mdi:clipboard-list-outline",
    href: "/admin/orders",
  },
  {
    page: "My Stocks",
    icon: "mdi:star-outline",
    href: "/admin/my-stocks",
  },
  {
    page: "Notifications",
    icon: "mdi:bell-outline",
    href: "/admin/notifications",
  },
  {
    page: "Copy Trading",
    icon: "mdi:account-cash-outline",
    href: "/admin/copy-trading",
  },
  {
    page: "Settings",
    icon: "mdi:cog-outline",
    href: "/admin/settings",
  },
];