"use client";

import { useEffect, useState } from "react";
import { adminApi } from "@/lib/api/backend";
import type { PaymentOrder } from "@/types/api";

export default function OrdersPage() {
  const [orders, setOrders] = useState<PaymentOrder[]>([]);
  const [details, setDetails] = useState<Record<string, string>>({});
  const [error, setError] = useState("");
  const load = async () => { try { setOrders(await adminApi.paymentOrders()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load orders"); } };
  useEffect(() => { void load(); }, []);
  const update = async (id: string, data: { methodDetails?: string; status?: "completed" | "rejected" }) => { try { await adminApi.updatePaymentOrder(id, data); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update order"); } };
  return <main className="space-y-6"><div><h1 className="text-2xl font-bold text-white">Payment Orders</h1><p className="text-sm text-penny-text-muted">Manage deposits and withdrawals from the backend.</p></div>{error && <p className="text-red-400">{error}</p>}<div className="space-y-4">{orders.map((order) => <article key={order._id} className="rounded-2xl p-5 bg-[#151d2d] border border-[#252f45]"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase text-[#00d4a1]">{order.type} · {order.method}</p><h2 className="text-lg font-bold text-white">${order.amount.toFixed(2)}</h2><p className="text-xs text-penny-text-muted">{order.email} · {order.status} · expires {new Date(order.expiresAt).toLocaleString()}</p></div><div className="flex gap-2"><button onClick={() => update(order._id, { status: "completed" })} disabled={order.status === "completed" || order.status === "rejected" || order.status === "expired"} className="px-3 py-2 rounded-lg bg-green-500/20 text-green-300 disabled:opacity-40">Approve</button><button onClick={() => update(order._id, { status: "rejected" })} disabled={order.status === "completed" || order.status === "rejected" || order.status === "expired"} className="px-3 py-2 rounded-lg bg-red-500/20 text-red-300 disabled:opacity-40">Reject</button></div></div>{order.type === "deposit" && order.status === "pending" && <div className="mt-4 flex gap-2"><input value={details[order._id] ?? ""} onChange={(e) => setDetails((current) => ({ ...current, [order._id]: e.target.value }))} placeholder="Payment account / wallet details" className="flex-1 p-2 rounded-lg bg-[#0d1624] text-white border border-[#252f45]"/><button onClick={() => update(order._id, { methodDetails: details[order._id] })} className="px-3 py-2 rounded-lg bg-[#00d4a1] text-[#0d1624] font-bold">Send details</button></div>}{order.methodDetails && <p className="mt-3 text-sm text-white whitespace-pre-wrap">Details: {order.methodDetails}</p>}{order.proofPaymentDocument && <p className="mt-2 text-xs text-[#00d4a1]">Payment proof attached to transaction.</p>}</article>)}{orders.length === 0 && <p className="text-penny-text-muted">No payment orders found.</p>}</div></main>;
}
